services:
  - type: web
    name: greencart-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn django_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_backend.settings
      - key: DATABASE_URL
        fromDatabase:
          name: greencart-db
          property: connectionString
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: greencart-backend-xxxx.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend.onrender.com
      - key: STRIPE_SECRET_KEY
        value: your-stripe-secret
      - key: STRIPE_PUBLISHABLE_KEY
        value: your-stripe-publishable-key
      - key: STRIPE_WEBHOOK_SECRET
        value: your-stripe-webhook-secret
      - key: RENDER
        value: true
